version: '3.5'

services:
  nuudel-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nuudel-server
    environment:
      env_file: .env
      NODE_ENV: production
    ports:
      - '8080:8080'
