export enum Country {
  Mongolia = 'Mongolia',
  Belgium = 'Belgium',
  China = 'China',
  Canada = 'Canada',
  France = 'France',
  Germany = 'Germany',
  Italy = 'Italy',
  Japan = 'Japan',
  Korea = 'Korea',
  Netherlands = 'Netherlands',
  Poland = 'Poland',
  Portugal = 'Portugal',
  Russia = 'Russia',
  Spain = 'Spain',
  Singapore = 'Singapore',
  Turkey = 'Turkey',
  UK = 'UK',
  USA = 'USA',
}
