export enum Currency {
  MNT = 'MNT',
  USD = 'USD',
  /*
  EUR = 'EUR',
  CNY = 'CNY',
  KRW = 'KRW',
  TRY = 'TRY',
  RUB = 'RUB',
  JPY = 'JPY',
  GBP = 'GBP',
  CAD = 'CAD',
  SGD = 'SGD',
  AED	= 'AED',	 // United Arab Emirates Dirham
  AMD	= 'AMD',	 // Armenian Dram
  ARS	= 'ARS',	 // Argentine Peso
  AUD	= 'AUD',	 // Australian Dollar
  AWG	= 'AWG',	 // Aruban Florin
  AZN	= 'AZN',	 // Azerbaijani Manat
  BGN	= 'BGN',	 // Bulgarian Lev
  BND	= 'BND',	 // Bruneian Dollar
  BOB	= 'BOB',	 // Bolivian Boliviano
  BRL	= 'BRL',	 // Brazilian Real
  BSD	= 'BSD',	 // Bahamian Dollar
  BZD	= 'BZD',	 // Belize Dollar
  CAD	= 'CAD',	 // Canadian Dollar
  CLP	= 'CLP',	 // Chilean Peso
  CNY	= 'CNY',	 // Chinese Yuan Renminbi
  COP	= 'COP',	 // Colombian Peso
  CRC	= 'CRC',	 // Costa Rican Colon
  DOP	= 'DOP',	 // Dominican Peso
  EGP	= 'EGP',	 // Egyptian Pound
  EUR	= 'EUR',	 // Euro
  GBP	= 'GBP',	 // British Pound
  GHS	= 'GHS',	 // Ghanaian Cedi
  GTQ	= 'GTQ',	 // Guatemalan Quetzal
  HKD	= 'HKD',	 // Hong Kong Dollar
  HNL	= 'HNL',	 // Honduran Lempira
  HUF	= 'HUF',	 // Hungarian Forint
  IDR	= 'IDR',	 // Indonesian Rupiah
  ILS	= 'ILS',	 // Israeli Shekel
  INR	= 'INR',	 // Indian Rupee
  JMD	= 'JMD',	 // Jamaican Dollar
  JPY	= 'JPY',	 // Japanese Yen
  KES	= 'KES',	 // Kenyan Shilling
  KHR	= 'KHR',	 // Cambodian Riel
  KRW	= 'KRW',	 // South Korean Won
  KYD	= 'KYD',	 // Caymanian Dollar
  KZT	= 'KZT',	 // Kazakhstani Tenge
  LBP	= 'LBP',	 // Lebanese Pound
  MAD	= 'MAD',	 // Moroccan Dirham
  MNT	= 'MNT',	 // Mongolian Tughrik
  MOP	= 'MOP',	 // Macanese Pataca
  MUR	= 'MUR',	 // Mauritian Rupee
  MXN	= 'MXN',	 // Mexican Peso
  MYR	= 'MYR',	 // Malaysian Ringgit
  NAD	= 'NAD',	 // Namibian Dollar
  NGN	= 'NGN',	 // Nigerian Naira
  NOK	= 'NOK',	 // Norwegian Krone
  NZD	= 'NZD',	 // New Zealand Dollar
  PAB	= 'PAB',	 // Panamanian Balboa
  PEN	= 'PEN',	 // Peruvian Sol
  PHP	= 'PHP',	 // Philippine Peso
  PYG	= 'PYG',	 // Paraguayan Guaraní
  QAR	= 'QAR',	 // Qatari Riyal
  RUB	= 'RUB',	 // Russian Ruble
  SAR	= 'SAR',	 // Saudi Arabian Riyal
  SGD	= 'SGD',	 // Singapore Dollar
  THB	= 'THB',	 // Thai Baht
  TRY	= 'TRY',	 // Turkish Lira
  TTD	= 'TTD',	 // Trinidadian Dollar
  TWD	= 'TWD',	 // Taiwan New Dollar
  TZS	= 'TZS',	 // Tanzanian Shilling
  USD	= 'USD',	 // United States Dollar
  UYU	= 'UYU',	 // Uruguayan Peso
  VND	= 'VND',	 // Vietnamese Dong
  XCD	= 'XCD',	 // Eastern Caribbean Dollar
  ZAR	= 'ZAR',	 // South African Rand // */
}
